/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 03 10:18:47 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.MergeSort;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MergeSort_ESTest extends MergeSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      MergeSort.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MergeSort mergeSort0 = new MergeSort();
      assertNotNull(mergeSort0);
      
      int[] intArray0 = new int[0];
      mergeSort0.sort(intArray0);
      assertArrayEquals(new int[] {}, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MergeSort mergeSort0 = new MergeSort();
      assertNotNull(mergeSort0);
      
      // Undeclared exception!
      try { 
        mergeSort0.sort((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.osu.cs362.MergeSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        MergeSort.main((String[]) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine("6sebBZh6Ng:[1>");
      // Undeclared exception!
      try { 
        MergeSort.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SystemInUtil.addInputLine("L-bB-0[Zjf");
      // Undeclared exception!
      try { 
        MergeSort.getInput();
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      int[] intArray0 = MergeSort.getInput();
      assertArrayEquals(new int[] {2, 2, 2, 2, 2, 2}, intArray0);
      assertNotNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        MergeSort.getInput();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("4");
      MergeSort.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MergeSort mergeSort0 = new MergeSort();
      int[] intArray0 = new int[7];
      intArray0[4] = (-1);
      mergeSort0.sort(intArray0);
      assertArrayEquals(new int[] {0, 0, (-1), 0, 0, 0, 0}, intArray0);
  }
}
